### PR TITLE
Add volume to mysql container

### PR DESCRIPTION
**Pull request by mmahrous**
Add volume to mysql container to save the data base in case anything happen

### CODE REVIEW

**Comment by marteinn** [comment]
Hi @mmahrous and thanks for the PR! On which systems have you tested the volume write? I'm asking because I have had permission issues when doing the same thing with PostgreSQL when running docker toolbox on MacOS.

**Comment by mmahrous** [comment]
Hello @marteinn I used Debian 8.7 x64, what kind of permission issue that you faced I use volume with all of my containers on MacOS.

**Comment by marteinn** [comment]
@mmahrous I did some further research and it seems like docker for mac solved that (unrelated) issue. Great to hear that it is tested on MacOS, I will talk with the team tomorrow about this PR before accepting, it would be nice to have a persistent db :)

**Comment by mmahrous** [comment]
great to hear that, yes cause I had a problem that I lost my database in production phase because of this and I managed to get it back from docker tmp volumes, anyway waiting for the merge :)

**Comment by mikaelengstrom** [comment]
@mmahrous, thanks!

@marteinn, i am fine with this. Lets merge?

**Comment by marteinn** [comment]
@mikaelengstrom Lets do it 👍

**Pull request merged**
